package com.piedpiper.sec02;

import com.piedpiper.util.Util;

import reactor.core.publisher.Flux;

public class Sec02FluxToMono {
	
	public static void main(String[] args) {
		
		//Here in the below pipeline we have a flux which generates elements from 1 to 10
		//the next()  call generates a Mono from the above flux.
		//so the mono waits for a single element and then pass a onComplete signal 
		//to the subscriber
		
		//So the subscriber prints a single element from the mono it subscribes to.
		
		//apart from this if we want a number other than the first number generated by
		// flux.....Taht is conditionally we want to get a number greater than 3
		//we can filer on the flux as below
		
		Flux.range(0, 10)
		.filter(i -> i > 3)
		.next()
		.subscribe(Util.onNext(),Util.onError(),Util.onComplete());
	}

}
